version: "3"  
services:
  traefik:  
    image: traefik:latest  
    container_name: traefik  
    depends_on:  
      - "ztncui"  
    ports:  
      - "80:80"  
      - "443:443"  
    volumes:  
      - "/zerotraefik:/etc/traefik"  
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  
    restart: always  
  
  ztncui:  
    image: keynetworks/ztncui:latest  
    container_name: ztncui  
    ports:  
      - "3180:3180"
      - "9993:9993/udp"  
    volumes:  
      - /mydata/ztncui:/opt/key-networks/ztncui/etc  
      - /mydata/zt1:/var/lib/zerotier-one  
    restart: always  
    environment:  
      - "NODE_ENV=production"  
      - "HTTP_ALL_INTERFACES=yes"  
      - "HTTP_PORT=8000"  
      - "ZTNCUI_PASSWD="  
      - "MYDOMAIN="  
    labels:  
      - "traefik.enable=true"  
      - "traefik.http.routers.ztncui.entrypoints=web, websecure"  
      - "traefik.http.routers.ztncui.rule=Host(``)"  
      - "traefik.http.routers.ztncui.tls=True"  
      - "traefik.http.services.ztncui.loadbalancer.server.port=8000"
